version: '3.4'

services:
  ticketbooking.webapi:
    image: ${DOCKER_REGISTRY-}ticketbookingwebapi
    build:
      context: .
      dockerfile: TicketBooking.WebAPI\Dockerfile
    ports: 
      - "8080:80"
    depends_on:
      - db
   
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
       
    environment:
      SA_PASSWORD: "securePassword1*"
      ACCEPT_EULA: "Y"