version: '3.4'

services:      
  client:
    image: client
    build: 
      context: ./react-ticket-booking-app
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    networks:
      - mynet      
    depends_on:
      - ticketbookingapi
      - identityapi

  identityapi:
    image: identityapi
    build: 
      context: ./IdentityServer
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
      - ASPNETCORE_HTTP_PORTS=8000
    networks:
      - mynet
    depends_on:
      - db2
      
  ticketbookingapi:
    image: ticketbookingapi
    build:
      context: ./TicketBookingAPI
      dockerfile: TicketBooking.WebAPI\Dockerfile
    ports: 
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynet
    depends_on:
      - db  
   
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "securePassword1*"
      ACCEPT_EULA: "Y"
    networks:
      - mynet
      
  db2:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1434:1434"
    environment:
      SA_PASSWORD: "securePassword1*"
      ACCEPT_EULA: "Y"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge